### ISSUE TITLE
How do I delete or change associated discord account?

### ISSUE THREAD

**Issue by SamIAmPHX** [Ioni14/starcitizen-fleet-manager#11]
Didn't notice that I was logged into the web version of Discord with an alt account. Now I can't change it to the correct account.

**Comment by Ioni14** [comment]
Thanks for the report, we are working on a solution to this issue.
For now, I unlink your account. So, normally you can now link your RSI account.
Sorry for the inconvenience.

**Comment by SamIAmPHX** [comment]
Thanks!
