### ISSUE TITLE
Not all ships are uploaded from Game Packages or standalone Ships

### ISSUE THREAD

**Issue by thezepter** [Ioni14/starcitizen-fleet-manager#14]
Not all ships are uploaded from my Game Packages and not all standalone ships will be uploaded. 
Thanks for this great tool !

Missing in my Fleet:

Standalone Ships:__________ Carrack
Game Packages:____________ MISC Endeavor (Rear Admiral LTI Package)

**Comment by Ioni14** [comment]
Hello and thanks for reporting. :)

Could you give me your Star Citizen Handle please? This will help me to find the bug.

Moreover, would it be possible to screenshot this game package pledge (with Carrack visible) from your RSI Hangar? You can, of course, hide price or other "sensitive" infos. Maybe it's the ship parsing that doesn't work.

**Comment by thezepter** [comment]
Hello,
thanks.. i contact you on discord.

**Comment by thezepter** [comment]
Bug fixed. Thank you very much
