### ISSUE TITLE
talking about personnal privacy - maybe improvements ?

### ISSUE THREAD

**Issue by NightyLive** [Ioni14/starcitizen-fleet-manager#15]
I saw a video ashuvid made about your tool, claiming our personnal data privacy is the priority number one. Great for sure, the tool also, but some points is irritating me and a dont see any technical reasons :

- Why do we ABSOLUTELY need to link our Discord account ? Why can't we juste register with a classic login/mail/password ? Allowing to do it is nice but making it mandatory is not. I don't really you to know my Discord account.

- Why do we ABSOLUTELY need to use your addons ? Just allowing us to add ship manualy from a list of choice is enough, even people with a lot of ship would have to do the whole step only once, later it would be only adding or removing 1-2 or maybe 3 ships. I would prefer this by far than using addons that are collectling our datas.

- I understand about linking our handle, but well, for the same privacy reason it would be simple for the corp users to apply to a corp, and the manager will just need to accept or deny them, without linking any account. So why making the handle linking way the only one ?

Please let us choice, most of us are far from kiddies that need one-click-button solution to handle our fleet, I'm sure your application would have more success with that.

**Comment by vyrtualsynthese** [comment]
First point : Simple register system is coming soon.
Second point : Manual management is coming soon.
Third point : Need to think about it but we focused on the simplest usage possible.

Thanks for the feedback ^^
