### ISSUE TITLE
Star Citizen Hanger XPLORer / Fleet Mgr fight for the same screen real estate

### ISSUE THREAD

**Issue by Brdrker** [Ioni14/starcitizen-fleet-manager#16]
I am now running both of these. Unless I really, REALLY expand my screen real estate for the browsers use, they overlap. It appears that XPLORer binds to the left side of the browser and Flight Mgr is locked into place, so there is a work around by expanding the browser size. Is there a way you could enable a control as to where to actually bind it's location in order to avoid the overlap?

![FleetMgrXPLORerOverlap](https://user-images.githubusercontent.com/21250895/70146445-228c7500-1670-11ea-8d2e-c0c1d964e9cf.JPG)

**Comment by Ioni14** [comment]
Done in the last version of the extension. ;)
