### ISSUE TITLE
Issue when trying to start/build the docker

### ISSUE THREAD

**Issue by louga31** [Ioni14/starcitizen-fleet-manager#17]
When I do `make up`,

I get this issue at Step 44/70:

`Step 44/70 : RUN mkdir -p public/bundles     && bin/console assets:install -v     && rm -fr var/cache/*     && bin/console cache:warmup -v     && mkdir -p var/log && chown -R www-data var/log
 ---> Running in 13f18d31d91a
': No such file or directory
ERROR: Service 'php' failed to build: The command '/bin/sh -c mkdir -p public/bundles     && bin/console assets:install -v     && rm -fr var/cache/*     && bin/console cache:warmup -v     && mkdir -p var/log && chown -R www-data var/log' returned a non-zero code: 127`

Do you know any way to fix it ?
Thanks in advance

**Comment by vyrtualsynthese** [comment]
Looks strange, during the stage the folder should be existing. Are your running docker on linux ?

**Comment by louga31** [comment]
I tried on both Linux and Windows with linux type docker

**Comment by vyrtualsynthese** [comment]
Never runned the project localy but using tools like Docker Dive can you check where is the file supposed to come from and if it actualy exist.
I may be and error or bad behavior comming from an earlier stage who should generate the required folder but dont then it crashes when the folder is used.

**Comment by louga31** [comment]
Update, my Debian docker was probably in a bad install, after a complete wipe, it works. On Windows with Linux docker, it still didn't work.

Now, it seems that the docker have an issue with the database.

![Login with Discord](https://user-images.githubusercontent.com/23664359/70937836-58086980-2045-11ea-9ee7-54fbda76abe9.png)
![Trying to register](https://user-images.githubusercontent.com/23664359/70937904-7a01ec00-2045-11ea-8fb7-6fdfdf7f8997.png)
