### ISSUE TITLE
Enhancement Request (ship costing)

### ISSUE THREAD

**Issue by Brdrker** [Ioni14/starcitizen-fleet-manager#18]
First off, the latest patches have fixed it all the issues (1k price, etc.). As I've added a few ships since your fixes, all the updates have gone perfectly. 

I found some oddities (I got the multi-Ares package) in the data and, while not critical to the performance of the tool, it does introduce some inaccuracy. For example, my data has two Ranger CV's. JSON below:

{
    "name": "Ranger CV",
    "manufacturer": "Tumbril",
    "id": "18192862",
    "cost": "$30.00 USD",
    "lti": true,
    "monthsInsurance": null,
    "package_id": "18192862",
    "pledge": "Standalone Ship - Tumbril Ranger CV Warbond ",
    "pledge_date": "May 13, 2019",
    "warbond": true
  },

and

{
    "name": "Ranger CV",
    "manufacturer": "Tumbril",
    "id": "18167816",
    "cost": "$85.00 USD",
    "lti": true,
    "monthsInsurance": null,
    "package_id": "18167816",
    "pledge": "Add-Ons - Sons of Centauri Pack Warbond   ",
    "pledge_date": "May 10, 2019",
    "warbond": true
  },

The second Ranger CV was part of a Pack of 3 Ranger's (TR, CV, and RC - Sons of Centauri Pack). If you bought the pack of all three, you got a deal. But if I melt one of those, it's melt value is, as of now, $30, not $85.  The same is true of the Ares Pack currently available for $355. 

Now, honestly, this is data that is "poisoned" of a fashion by SC and, as you stated in our prior communication, maybe with an API, you can actually query the "real" cost of the ships as the cost data isn't really helping you out here. That means, alas, you'd have to keep track of packages and what the actual product cost was and, maybe worse, what the cost was "at the time" since we all know prices are going up over time.

Thus, I'm not really asking you for a fix but simply bringing it to your attention as a "nice to have."

**Comment by Ioni14** [comment]
We are reworking Fleet Manager, there is no longer JSON upload.
