### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by YGwen** [Ioni14/starcitizen-fleet-manager#2]
On page : https://fleet.fallkrom.space/#/my-fleet

Image is missing for : 

- Nova Tank
- Drake Kraken

**Comment by Reykira** [comment]
Same issue on this page : https://fleet.fallkrom.space/#/my-fleet
- Arrow is missing

**Comment by Xungames** [comment]
Same issue for :

- 325a Fighter

- Reliant Kore

**Comment by vyrtualsynthese** [comment]
Fixed in the next version.
Thanks alot for your help.
