### ISSUE TITLE
Priority issue when ships have multiple insurances

### ISSUE THREAD

**Issue by dixonte** [Ioni14/starcitizen-fleet-manager#26]
I have a game package that has lifetime insurance. However, because I applied an upgrade during the expo event it also picked up the 120 month insurance tag. I've contacted support about this and they said at a later date the lesser insurance would be removed, leaving the lifetime insurance.

It would be nice if Fleet Manager handled this better. Either displaying both; or by having higher month numbers trump lower, with LTI trumping all.

**Comment by Ioni14** [comment]
Hello, we are reworking Fleet Manager. The new version won't have the insurance at first. But when we will add it, you will have total control on this.
