### ISSUE TITLE
Problem of title being cutted

### ISSUE THREAD

**Issue by Reykira** [Ioni14/starcitizen-fleet-manager#3]
The title "SC Fleet manager" on the upper left side of the menu is cutted. A piece of the S is not appearing.
Maybe a problem of resolution ? 
I have a 17" 1080p screen.

**Comment by vyrtualsynthese** [comment]
On what browser and which version are you using the app ?

Sorry for the late reply

**Comment by vyrtualsynthese** [comment]
Unable to reproduce
