### ISSUE TITLE
just 6/10 ships in my corpo's fleets

### ISSUE THREAD

**Issue by FrereCasto** [Ioni14/starcitizen-fleet-manager#5]
[shiplist.txt](https://github.com/Ioni14/starcitizen-fleet-manager/files/3025323/shiplist.txt)

This is the json (renamed txt) : you'll see that only 6 of the 10 ships are listed in all the corpo's fleet manager.

**Comment by vyrtualsynthese** [comment]
Fixed in the next version thanks.
